POST http://localhost:8080/person
Content-Type: application/json

{
  "name": "JACF",
  "age": 222
}

###
GET http://localhost:8080/person/62373790fb08b023054d65c8


###
#not found
GET http://localhost:8080/person/6229a38236d4dc3abf0f3175

###
GET http://localhost:8080/person


###
PUT http://localhost:8080/person/62373790fb08b023054d65c8
Content-Type: application/json

{
  "name": "New Jorge",
  "age": 25
}

###
GET http://localhost:8080/person/search?name=Jorge&age=24

###
DELETE http://localhost:8080/person/623737c4fb08b023054d65c9
